version: "3.9"
services:
  omnix-handler:
    build: .
    container_name: omnix-handler
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - remnawave-network
    env_file:
      - .env

networks:
    remnawave-network:
        name: remnawave-network
        driver: bridge
        external: true